name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore
jobs:
  auto-cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/auto-cancel-redundant-job@v1
  build-ubuntu-1604:
    needs: auto-cancel
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        swift: 
        - "3.1"
        - "4.0"
        - "4.1"
        - "4.2"
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - run: swift --version
    - uses: actions/checkout@v2
    - run: swift build
  build-ubuntu-1804:
    needs: auto-cancel
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        swift: 
        - "5.0"
        - "5.1"
        - "5.2"
        - "5.3"
        - "5.4"
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - run: swift --version
    - uses: actions/checkout@v2
    - run: swift build
  test:
    needs: [build-ubuntu-1604, build-ubuntu-1804]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift --version
      - run: xcodebuild -scheme PromiseKit test
